In [1]:
from netCDF4 import Dataset, Variable
import matplotlib.path as mpath
import cartopy
import xarray
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcol
import matplotlib.cm as cm
import matplotlib.ticker as mticker
from matplotlib.gridspec import GridSpec
import os
import nctoolkit as nct
import regex
from matplotlib.ticker import FormatStrFormatter
from matplotlib.ticker import StrMethodFormatter
import matplotlib.patches as mpatches
from cartopy.util import add_cyclic_point
from matplotlib import colors
import geopandas as gpd
import shapely.geometry as shp
import shapely.ops as ops
import rioxarray
import pyproj
import pandas as pd
from matplotlib.offsetbox import AnchoredText
import matplotlib as mpl
import glob

nctoolkit is using Climate Data Operators version 1.9.8

In [2]:
nct.deep_clean()

In [3]:
os.chdir('/media/jasmine/Album/Project/')
print(os.getcwd())

/media/jasmine/Album/Project

In [4]:
model = "Multimodel"
print(model)
experiment = "ssp585"
print(experiment)

Multimodel
ssp585

## Whole region

In [8]:
df = pd.DataFrame(columns=['Model','Variable', 'Percentage change','Absolute change'])
df

Empty DataFrame
Columns: [Model, Variable, Percentage change, Absolute change]
Index: []

In [49]:
df = pd.read_csv("csv/Whole_change.csv")
df = df.replace("Mixed layer depth", "MLD")
df = df.replace("Surface temperature", "SST")
df = df.replace("Sea ice cover", "Sea ice fraction")
df

            Model          Variable  Percentage change  Absolute change
0   ACCESS-ESM1-5              Iron              -2.47    -1.483000e+10
1   ACCESS-ESM1-5            Export              24.96     2.260000e+00
2   ACCESS-ESM1-5               NPP              27.24     1.941602e+09
3   ACCESS-ESM1-5               MLD             -15.45    -1.034000e+01
4   ACCESS-ESM1-5               PAR              10.13     6.170000e+00
5   ACCESS-ESM1-5           Nitrate              -4.08    -1.090000e+03
6   ACCESS-ESM1-5               SST               0.42     1.150000e+00
7   ACCESS-ESM1-5  Sea ice fraction             -60.34    -1.588000e+01
8       CMCC-ESM2            Export              11.11     2.680000e+00
9       CMCC-ESM2              Iron               9.43     1.758000e+10
10      CMCC-ESM2            Diatom              16.63     2.214108e+09
11      CMCC-ESM2               NPP              16.16     2.384424e+09
12      CMCC-ESM2           Nitrate              -6.46    -1.570000e+03
13      CMCC-ESM2               MLD              -8.44    -6.940000e+00
14      CMCC-ESM2               PAR               4.46     2.630000e+00
15      CMCC-ESM2               SST               0.33     9.000000e-01
16      CMCC-ESM2  Sea ice fraction             -64.70    -1.341000e+01
17   EC-Earth3-CC            Export               5.54     1.040000e+00
18   EC-Earth3-CC            Diatom               7.00     5.071632e+08
19   EC-Earth3-CC               NPP              12.73     2.350361e+09
20   EC-Earth3-CC               MLD             -14.98    -8.520000e+00
21   EC-Earth3-CC               PAR               5.68     4.380000e+00
22   EC-Earth3-CC           Nitrate              -3.55    -9.600000e+02
23   EC-Earth3-CC               SST               0.50     1.380000e+00
24   EC-Earth3-CC  Sea ice fraction             -89.42    -1.290000e+01
25   IPSL-CM6A-LR            Export               0.52     9.000000e-02
26   IPSL-CM6A-LR              Iron             -16.75    -5.254000e+10
27   IPSL-CM6A-LR            Diatom              -2.07    -1.627464e+08
28   IPSL-CM6A-LR               NPP              10.68     1.672882e+09
29   IPSL-CM6A-LR           Nitrate              -5.90    -1.620000e+03
30   IPSL-CM6A-LR               MLD             -13.35    -8.580000e+00
31   IPSL-CM6A-LR               SST               0.53     1.450000e+00
32   IPSL-CM6A-LR  Sea ice fraction             -55.47    -1.702000e+01
33   IPSL-CM6A-LR               PAR              12.26     6.200000e+00
34  MPI-ESM1-2-HR            Export               4.77     7.600000e-01
35  MPI-ESM1-2-HR              Iron              -1.58    -5.500000e+09
36  MPI-ESM1-2-HR               MLD             -18.06    -1.025000e+01
37  MPI-ESM1-2-HR               NPP               4.38     2.138412e+09
38  MPI-ESM1-2-HR               PAR              -1.13    -7.200000e-01
39  MPI-ESM1-2-HR           Nitrate               0.08     1.000000e+01
40  MPI-ESM1-2-HR               SST               0.25     6.700000e-01
41  MPI-ESM1-2-HR  Sea ice fraction             -53.12    -9.090000e+00
42   EC-Earth3-CC              Iron              -4.41    -1.055000e+01

In [50]:
for i in range(len(df["Absolute change"])):
    if df["Variable"][i] == "Nitrate":
        df["Absolute change"][i] = df["Absolute change"][i]/1000
    if df["Variable"][i] == "Iron":
        df["Absolute change"][i] = df["Absolute change"][i]/1e+9
    if df["Variable"][i] == "Diatom":
        df["Absolute change"][i] = df["Absolute change"][i]/ 12 / 3.154e+7
    if df["Variable"][i] == "NPP":
        df["Absolute change"][i] = df["Absolute change"][i]/ 12 / 3.154e+7

df

/tmp/ipykernel_135782/851134988.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_135782/851134988.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_135782/851134988.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_135782/851134988.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

            Model          Variable  Percentage change  Absolute change
0   ACCESS-ESM1-5              Iron              -2.47    -1.483000e+01
1   ACCESS-ESM1-5            Export              24.96     2.260000e+00
2   ACCESS-ESM1-5               NPP              27.24     5.130000e+00
3   ACCESS-ESM1-5               MLD             -15.45    -1.034000e+01
4   ACCESS-ESM1-5               PAR              10.13     6.170000e+00
5   ACCESS-ESM1-5           Nitrate              -4.08    -1.090000e+00
6   ACCESS-ESM1-5               SST               0.42     1.150000e+00
7   ACCESS-ESM1-5  Sea ice fraction             -60.34    -1.588000e+01
8       CMCC-ESM2            Export              11.11     2.680000e+00
9       CMCC-ESM2              Iron               9.43     1.758000e+01
10      CMCC-ESM2            Diatom              16.63     5.850000e+00
11      CMCC-ESM2               NPP              16.16     6.300000e+00
12      CMCC-ESM2           Nitrate              -6.46    -1.570000e+00
13      CMCC-ESM2               MLD              -8.44    -6.940000e+00
14      CMCC-ESM2               PAR               4.46     2.630000e+00
15      CMCC-ESM2               SST               0.33     9.000000e-01
16      CMCC-ESM2  Sea ice fraction             -64.70    -1.341000e+01
17   EC-Earth3-CC            Export               5.54     1.040000e+00
18   EC-Earth3-CC            Diatom               7.00     1.340000e+00
19   EC-Earth3-CC               NPP              12.73     6.210000e+00
20   EC-Earth3-CC               MLD             -14.98    -8.520000e+00
21   EC-Earth3-CC               PAR               5.68     4.380000e+00
22   EC-Earth3-CC           Nitrate              -3.55    -9.600000e-01
23   EC-Earth3-CC               SST               0.50     1.380000e+00
24   EC-Earth3-CC  Sea ice fraction             -89.42    -1.290000e+01
25   IPSL-CM6A-LR            Export               0.52     9.000000e-02
26   IPSL-CM6A-LR              Iron             -16.75    -5.254000e+01
27   IPSL-CM6A-LR            Diatom              -2.07    -4.300000e-01
28   IPSL-CM6A-LR               NPP              10.68     4.420000e+00
29   IPSL-CM6A-LR           Nitrate              -5.90    -1.620000e+00
30   IPSL-CM6A-LR               MLD             -13.35    -8.580000e+00
31   IPSL-CM6A-LR               SST               0.53     1.450000e+00
32   IPSL-CM6A-LR  Sea ice fraction             -55.47    -1.702000e+01
33   IPSL-CM6A-LR               PAR              12.26     6.200000e+00
34  MPI-ESM1-2-HR            Export               4.77     7.600000e-01
35  MPI-ESM1-2-HR              Iron              -1.58    -5.500000e+00
36  MPI-ESM1-2-HR               MLD             -18.06    -1.025000e+01
37  MPI-ESM1-2-HR               NPP               4.38     5.650000e+00
38  MPI-ESM1-2-HR               PAR              -1.13    -7.200000e-01
39  MPI-ESM1-2-HR           Nitrate               0.08     1.000000e-02
40  MPI-ESM1-2-HR               SST               0.25     6.700000e-01
41  MPI-ESM1-2-HR  Sea ice fraction             -53.12    -9.090000e+00
42   EC-Earth3-CC              Iron              -4.41    -1.055000e-08

In [54]:
df.at[42, 'Absolute change'] = (df[-1:]["Absolute change"] * 1e+9).values

In [36]:
for i in range(len(df["Absolute change"])):
    if df["Variable"][i] == "Nitrate":
        df["Absolute change"][i] = df["Absolute change"][i]*1000
    if df["Variable"][i] == "Iron":
        df["Absolute change"][i] = df["Absolute change"][i]*1e+9
    if df["Variable"][i] == "Diatom":
        df["Absolute change"][i] = df["Absolute change"][i]* 12 * 3.154e+7
    if df["Variable"][i] == "NPP":
        df["Absolute change"][i] = df["Absolute change"][i]* 12 * 3.154e+7

df

/tmp/ipykernel_135782/3638443720.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_135782/3638443720.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_135782/3638443720.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_135782/3638443720.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

            Model          Variable  Percentage change  Absolute change
0   ACCESS-ESM1-5              Iron              -2.47    -1.483000e+19
1   ACCESS-ESM1-5            Export              24.96     2.260000e+00
2   ACCESS-ESM1-5               NPP              27.24     7.348577e+17
3   ACCESS-ESM1-5               MLD             -15.45    -1.034000e+01
4   ACCESS-ESM1-5               PAR              10.13     6.170000e+00
5   ACCESS-ESM1-5           Nitrate              -4.08    -1.090000e+06
6   ACCESS-ESM1-5               SST               0.42     1.150000e+00
7   ACCESS-ESM1-5  Sea ice fraction             -60.34    -1.588000e+01
8       CMCC-ESM2            Export              11.11     2.680000e+00
9       CMCC-ESM2              Iron               9.43     1.758000e+19
10      CMCC-ESM2            Diatom              16.63     8.379956e+17
11      CMCC-ESM2               NPP              16.16     9.024568e+17
12      CMCC-ESM2           Nitrate              -6.46    -1.570000e+06
13      CMCC-ESM2               MLD              -8.44    -6.940000e+00
14      CMCC-ESM2               PAR               4.46     2.630000e+00
15      CMCC-ESM2               SST               0.33     9.000000e-01
16      CMCC-ESM2  Sea ice fraction             -64.70    -1.341000e+01
17   EC-Earth3-CC            Export               5.54     1.040000e+00
18   EC-Earth3-CC            Diatom               7.00     1.919511e+17
19   EC-Earth3-CC               NPP              12.73     8.895646e+17
20   EC-Earth3-CC               MLD             -14.98    -8.520000e+00
21   EC-Earth3-CC               PAR               5.68     4.380000e+00
22   EC-Earth3-CC           Nitrate              -3.55    -9.600000e+05
23   EC-Earth3-CC               SST               0.50     1.380000e+00
24   EC-Earth3-CC  Sea ice fraction             -89.42    -1.290000e+01
25   IPSL-CM6A-LR            Export               0.52     9.000000e-02
26   IPSL-CM6A-LR              Iron             -16.75    -5.254000e+19
27   IPSL-CM6A-LR            Diatom              -2.07    -6.159626e+16
28   IPSL-CM6A-LR               NPP              10.68     6.331522e+17
29   IPSL-CM6A-LR           Nitrate              -5.90    -1.620000e+06
30   IPSL-CM6A-LR               MLD             -13.35    -8.580000e+00
31   IPSL-CM6A-LR               SST               0.53     1.450000e+00
32   IPSL-CM6A-LR  Sea ice fraction             -55.47    -1.702000e+01
33   IPSL-CM6A-LR               PAR              12.26     6.200000e+00
34  MPI-ESM1-2-HR            Export               4.77     7.600000e-01
35  MPI-ESM1-2-HR              Iron              -1.58    -5.500000e+18
36  MPI-ESM1-2-HR               MLD             -18.06    -1.025000e+01
37  MPI-ESM1-2-HR               NPP               4.38     8.093462e+17
38  MPI-ESM1-2-HR               PAR              -1.13    -7.200000e-01
39  MPI-ESM1-2-HR           Nitrate               0.08     1.000000e+04
40  MPI-ESM1-2-HR               SST               0.25     6.700000e-01
41  MPI-ESM1-2-HR  Sea ice fraction             -53.12    -9.090000e+00
42   EC-Earth3-CC              Iron              -4.41    -1.055000e+10

In [55]:
df = df.round({"Percentage change":2, "Absolute change":2})
df

            Model          Variable  Percentage change  Absolute change
0   ACCESS-ESM1-5              Iron              -2.47           -14.83
1   ACCESS-ESM1-5            Export              24.96             2.26
2   ACCESS-ESM1-5               NPP              27.24             5.13
3   ACCESS-ESM1-5               MLD             -15.45           -10.34
4   ACCESS-ESM1-5               PAR              10.13             6.17
5   ACCESS-ESM1-5           Nitrate              -4.08            -1.09
6   ACCESS-ESM1-5               SST               0.42             1.15
7   ACCESS-ESM1-5  Sea ice fraction             -60.34           -15.88
8       CMCC-ESM2            Export              11.11             2.68
9       CMCC-ESM2              Iron               9.43            17.58
10      CMCC-ESM2            Diatom              16.63             5.85
11      CMCC-ESM2               NPP              16.16             6.30
12      CMCC-ESM2           Nitrate              -6.46            -1.57
13      CMCC-ESM2               MLD              -8.44            -6.94
14      CMCC-ESM2               PAR               4.46             2.63
15      CMCC-ESM2               SST               0.33             0.90
16      CMCC-ESM2  Sea ice fraction             -64.70           -13.41
17   EC-Earth3-CC            Export               5.54             1.04
18   EC-Earth3-CC            Diatom               7.00             1.34
19   EC-Earth3-CC               NPP              12.73             6.21
20   EC-Earth3-CC               MLD             -14.98            -8.52
21   EC-Earth3-CC               PAR               5.68             4.38
22   EC-Earth3-CC           Nitrate              -3.55            -0.96
23   EC-Earth3-CC               SST               0.50             1.38
24   EC-Earth3-CC  Sea ice fraction             -89.42           -12.90
25   IPSL-CM6A-LR            Export               0.52             0.09
26   IPSL-CM6A-LR              Iron             -16.75           -52.54
27   IPSL-CM6A-LR            Diatom              -2.07            -0.43
28   IPSL-CM6A-LR               NPP              10.68             4.42
29   IPSL-CM6A-LR           Nitrate              -5.90            -1.62
30   IPSL-CM6A-LR               MLD             -13.35            -8.58
31   IPSL-CM6A-LR               SST               0.53             1.45
32   IPSL-CM6A-LR  Sea ice fraction             -55.47           -17.02
33   IPSL-CM6A-LR               PAR              12.26             6.20
34  MPI-ESM1-2-HR            Export               4.77             0.76
35  MPI-ESM1-2-HR              Iron              -1.58            -5.50
36  MPI-ESM1-2-HR               MLD             -18.06           -10.25
37  MPI-ESM1-2-HR               NPP               4.38             5.65
38  MPI-ESM1-2-HR               PAR              -1.13            -0.72
39  MPI-ESM1-2-HR           Nitrate               0.08             0.01
40  MPI-ESM1-2-HR               SST               0.25             0.67
41  MPI-ESM1-2-HR  Sea ice fraction             -53.12            -9.09
42   EC-Earth3-CC              Iron              -4.41           -10.55

In [56]:
df.to_csv("csv/Whole_change.csv", header = True, index= False)

### Presenting

In [62]:
df = pd.read_csv("csv/Whole_change.csv")
df = df.rename(columns={"Percentage change": "Percentage", "Absolute change": "Absolute"})
df

            Model          Variable  Percentage  Absolute
0   ACCESS-ESM1-5              Iron       -2.47    -14.83
1   ACCESS-ESM1-5            Export       24.96      2.26
2   ACCESS-ESM1-5               NPP       27.24      5.13
3   ACCESS-ESM1-5               MLD      -15.45    -10.34
4   ACCESS-ESM1-5               PAR       10.13      6.17
5   ACCESS-ESM1-5           Nitrate       -4.08     -1.09
6   ACCESS-ESM1-5               SST        0.42      1.15
7   ACCESS-ESM1-5  Sea ice fraction      -60.34    -15.88
8       CMCC-ESM2            Export       11.11      2.68
9       CMCC-ESM2              Iron        9.43     17.58
10      CMCC-ESM2            Diatom       16.63      5.85
11      CMCC-ESM2               NPP       16.16      6.30
12      CMCC-ESM2           Nitrate       -6.46     -1.57
13      CMCC-ESM2               MLD       -8.44     -6.94
14      CMCC-ESM2               PAR        4.46      2.63
15      CMCC-ESM2               SST        0.33      0.90
16      CMCC-ESM2  Sea ice fraction      -64.70    -13.41
17   EC-Earth3-CC            Export        5.54      1.04
18   EC-Earth3-CC            Diatom        7.00      1.34
19   EC-Earth3-CC               NPP       12.73      6.21
20   EC-Earth3-CC               MLD      -14.98     -8.52
21   EC-Earth3-CC               PAR        5.68      4.38
22   EC-Earth3-CC           Nitrate       -3.55     -0.96
23   EC-Earth3-CC               SST        0.50      1.38
24   EC-Earth3-CC  Sea ice fraction      -89.42    -12.90
25   IPSL-CM6A-LR            Export        0.52      0.09
26   IPSL-CM6A-LR              Iron      -16.75    -52.54
27   IPSL-CM6A-LR            Diatom       -2.07     -0.43
28   IPSL-CM6A-LR               NPP       10.68      4.42
29   IPSL-CM6A-LR           Nitrate       -5.90     -1.62
30   IPSL-CM6A-LR               MLD      -13.35     -8.58
31   IPSL-CM6A-LR               SST        0.53      1.45
32   IPSL-CM6A-LR  Sea ice fraction      -55.47    -17.02
33   IPSL-CM6A-LR               PAR       12.26      6.20
34  MPI-ESM1-2-HR            Export        4.77      0.76
35  MPI-ESM1-2-HR              Iron       -1.58     -5.50
36  MPI-ESM1-2-HR               MLD      -18.06    -10.25
37  MPI-ESM1-2-HR               NPP        4.38      5.65
38  MPI-ESM1-2-HR               PAR       -1.13     -0.72
39  MPI-ESM1-2-HR           Nitrate        0.08      0.01
40  MPI-ESM1-2-HR               SST        0.25      0.67
41  MPI-ESM1-2-HR  Sea ice fraction      -53.12     -9.09
42   EC-Earth3-CC              Iron       -4.41    -10.55

In [64]:
df = pd.melt(df, id_vars=["Model", "Variable"], value_vars=["Percentage", "Absolute"],
             var_name='Type', value_name='Change')
df

            Model          Variable        Type  Change
0   ACCESS-ESM1-5              Iron  Percentage   -2.47
1   ACCESS-ESM1-5            Export  Percentage   24.96
2   ACCESS-ESM1-5               NPP  Percentage   27.24
3   ACCESS-ESM1-5               MLD  Percentage  -15.45
4   ACCESS-ESM1-5               PAR  Percentage   10.13
..            ...               ...         ...     ...
81  MPI-ESM1-2-HR               PAR    Absolute   -0.72
82  MPI-ESM1-2-HR           Nitrate    Absolute    0.01
83  MPI-ESM1-2-HR               SST    Absolute    0.67
84  MPI-ESM1-2-HR  Sea ice fraction    Absolute   -9.09
85   EC-Earth3-CC              Iron    Absolute  -10.55

[86 rows x 4 columns]

In [65]:
df = df.pivot_table(index="Variable", columns=["Model", "Type"], values=["Change"])
df

                        Change                                               \
Model            ACCESS-ESM1-5            CMCC-ESM2            EC-Earth3-CC
Type                  Absolute Percentage  Absolute Percentage     Absolute
Variable
Diatom                     NaN        NaN      5.85      16.63         1.34
Export                    2.26      24.96      2.68      11.11         1.04
Iron                    -14.83      -2.47     17.58       9.43       -10.55
MLD                     -10.34     -15.45     -6.94      -8.44        -8.52
NPP                       5.13      27.24      6.30      16.16         6.21
Nitrate                  -1.09      -4.08     -1.57      -6.46        -0.96
PAR                       6.17      10.13      2.63       4.46         4.38
SST                       1.15       0.42      0.90       0.33         1.38
Sea ice fraction        -15.88     -60.34    -13.41     -64.70       -12.90


Model                       IPSL-CM6A-LR            MPI-ESM1-2-HR
Type             Percentage     Absolute Percentage      Absolute Percentage
Variable
Diatom                 7.00        -0.43      -2.07           NaN        NaN
Export                 5.54         0.09       0.52          0.76       4.77
Iron                  -4.41       -52.54     -16.75         -5.50      -1.58
MLD                  -14.98        -8.58     -13.35        -10.25     -18.06
NPP                   12.73         4.42      10.68          5.65       4.38
Nitrate               -3.55        -1.62      -5.90          0.01       0.08
PAR                    5.68         6.20      12.26         -0.72      -1.13
SST                    0.50         1.45       0.53          0.67       0.25
Sea ice fraction     -89.42       -17.02     -55.47         -9.09     -53.12

In [66]:
df.to_csv("csv/Whole_change_final.csv")

In [67]:
df = pd.read_csv("csv/Whole_change_final.csv")
df

,Unnamed: 0,Change,Change.1,Change.2,Change.3,Change.4,Change.5,Change.6,Change.7,Change.8,Change.9
0,Model,ACCESS-ESM1-5,ACCESS-ESM1-5,CMCC-ESM2,CMCC-ESM2,EC-Earth3-CC,EC-Earth3-CC,IPSL-CM6A-LR,IPSL-CM6A-LR,MPI-ESM1-2-HR,MPI-ESM1-2-HR
1,Type,Absolute,Percentage,Absolute,Percentage,Absolute,Percentage,Absolute,Percentage,Absolute,Percentage
2,Variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Diatom,NaN,NaN,5.85,16.63,1.34,7.0,-0.43,-2.07,NaN,NaN
4,Export,2.26,24.96,2.68,11.11,1.04,5.54,0.09,0.52,0.76,4.77
5,Iron,-14.83,-2.47,17.58,9.43,-10.55,-4.41,-52.54,-16.75,-5.5,-1.58
6,MLD,-10.34,-15.45,-6.94,-8.44,-8.52,-14.98,-8.58,-13.35,-10.25,-18.06
7,NPP,5.13,27.24,6.3,16.16,6.21,12.73,4.42,10.68,5.65,4.38
8,Nitrate,-1.09,-4.08,-1.57,-6.46,-0.96,-3.55,-1.62,-5.9,0.01,0.08
9,PAR,6.17,10.13,2.63,4.46,4.38,5.68,6.2,12.26,-0.72,-1.13
10,SST,1.15,0.42,0.9,0.33,1.38,0.5,1.45,0.53,0.67,0.25
11,Sea ice fraction,-15.88,-60.34,-13.41,-64.7,-12.9,-89.42,-17.02,-55.47,-9.09,-53.12

## Zonal

In [12]:
df = pd.DataFrame(columns=['Model','Variable', 'Percentage change','Absolute change', "Zone"])
df

Empty DataFrame
Columns: [Model, Variable, Percentage change, Absolute change, Zone]
Index: []

In [95]:
df = pd.read_csv("csv/Zone_change.csv")
df = df.replace("Mixed layer depth", "MLD")
df = df.replace("Surface temperature", "SST")
df = df.replace("Sea ice cover", "Sea ice fraction")
df

            Model          Variable  Percentage change  Absolute change Zone
0   ACCESS-ESM1-5              Iron          -2.460000    -1.477000e+01  Inc
1   ACCESS-ESM1-5              Iron          -1.110000    -6.890000e+00  Dec
2   ACCESS-ESM1-5            Export          25.100000     2.270000e+00  Inc
3   ACCESS-ESM1-5            Export          -2.840000    -3.500000e-01  Dec
4   ACCESS-ESM1-5               NPP          27.310000     5.140000e+00  Inc
..            ...               ...                ...              ...  ...
81  MPI-ESM1-2-HR               SST           0.220000     6.000000e-01  Dec
82  MPI-ESM1-2-HR  Sea ice fraction         -52.980000    -1.113000e+01  Inc
83  MPI-ESM1-2-HR  Sea ice fraction         -69.690000    -6.050000e+00  Dec
84   EC-Earth3-CC              Iron          -3.334586    -6.049923e-09  Inc
85   EC-Earth3-CC              Iron         -11.066228    -2.535582e-08  Dec

[86 rows x 5 columns]

In [96]:
(df[-2:]["Absolute change"] * 1e+9).values[0]

-6.0499232290567315

In [97]:
df.at[85, 'Absolute change'] = (df[-2:]["Absolute change"] * 1e+9).values[1]
df.at[84, 'Absolute change'] = (df[-2:]["Absolute change"] * 1e+9).values[0]

In [44]:
for i in range(len(df["Absolute change"])):
    if df["Variable"][i] == "Nitrate":
        df["Absolute change"][i] = df["Absolute change"][i]*1000
    if df["Variable"][i] == "Iron":
        df["Absolute change"][i] = df["Absolute change"][i]*1e+9
    if df["Variable"][i] == "Diatom":
        df["Absolute change"][i] = df["Absolute change"][i]* 12 * 3.154e+7
    if df["Variable"][i] == "NPP":
        df["Absolute change"][i] = df["Absolute change"][i]* 12 * 3.154e+7

df

/tmp/ipykernel_6694/3638443720.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_6694/3638443720.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_6694/3638443720.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_6694/3638443720.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

            Model          Variable  Percentage change  Absolute change Zone
0   ACCESS-ESM1-5              Iron          -2.462672       -14.771047  Inc
1   ACCESS-ESM1-5              Iron          -1.107071        -6.892265  Dec
2   ACCESS-ESM1-5            Export          25.104570         2.268846  Inc
3   ACCESS-ESM1-5            Export          -2.837506        -0.347143  Dec
4   ACCESS-ESM1-5               NPP          27.305784         5.142289  Inc
..            ...               ...                ...              ...  ...
79  MPI-ESM1-2-HR           Nitrate           2.220648         0.386325  Dec
80  MPI-ESM1-2-HR               SST           0.254590         0.693298  Inc
81  MPI-ESM1-2-HR               SST           0.218396         0.597153  Dec
82  MPI-ESM1-2-HR  Sea ice fraction         -52.975853       -11.125512  Inc
83  MPI-ESM1-2-HR  Sea ice fraction         -69.688301        -6.052403  Dec

[84 rows x 5 columns]

In [98]:
df = df.round({"Percentage change":2, "Absolute change":2})
df.tail()

            Model          Variable  Percentage change  Absolute change Zone
81  MPI-ESM1-2-HR               SST               0.22             0.60  Dec
82  MPI-ESM1-2-HR  Sea ice fraction             -52.98           -11.13  Inc
83  MPI-ESM1-2-HR  Sea ice fraction             -69.69            -6.05  Dec
84   EC-Earth3-CC              Iron              -3.33            -6.05  Inc
85   EC-Earth3-CC              Iron             -11.07           -25.36  Dec

In [99]:
df.to_csv("csv/Zone_change.csv", header = True, index= False)

### Presenting

In [101]:
df = pd.read_csv("csv/Zone_change.csv")
df = df.rename(columns={"Percentage change": "Percentage", "Absolute change": "Absolute"})
df

            Model          Variable  Percentage  Absolute Zone
0   ACCESS-ESM1-5              Iron       -2.46    -14.77  Inc
1   ACCESS-ESM1-5              Iron       -1.11     -6.89  Dec
2   ACCESS-ESM1-5            Export       25.10      2.27  Inc
3   ACCESS-ESM1-5            Export       -2.84     -0.35  Dec
4   ACCESS-ESM1-5               NPP       27.31      5.14  Inc
..            ...               ...         ...       ...  ...
81  MPI-ESM1-2-HR               SST        0.22      0.60  Dec
82  MPI-ESM1-2-HR  Sea ice fraction      -52.98    -11.13  Inc
83  MPI-ESM1-2-HR  Sea ice fraction      -69.69     -6.05  Dec
84   EC-Earth3-CC              Iron       -3.33     -6.05  Inc
85   EC-Earth3-CC              Iron      -11.07    -25.36  Dec

[86 rows x 5 columns]

In [104]:
df = pd.melt(df, id_vars=["Model", "Variable", "Zone"], value_vars=["Percentage", "Absolute"],
             var_name='Type', value_name='Change')
df

             Model          Variable Zone        Type  Change
0    ACCESS-ESM1-5              Iron  Inc  Percentage   -2.46
1    ACCESS-ESM1-5              Iron  Dec  Percentage   -1.11
2    ACCESS-ESM1-5            Export  Inc  Percentage   25.10
3    ACCESS-ESM1-5            Export  Dec  Percentage   -2.84
4    ACCESS-ESM1-5               NPP  Inc  Percentage   27.31
..             ...               ...  ...         ...     ...
167  MPI-ESM1-2-HR               SST  Dec    Absolute    0.60
168  MPI-ESM1-2-HR  Sea ice fraction  Inc    Absolute  -11.13
169  MPI-ESM1-2-HR  Sea ice fraction  Dec    Absolute   -6.05
170   EC-Earth3-CC              Iron  Inc    Absolute   -6.05
171   EC-Earth3-CC              Iron  Dec    Absolute  -25.36

[172 rows x 5 columns]

In [105]:
df = df.pivot_table(index="Variable", columns=["Model", "Type", "Zone"], values=["Change"])
df

                        Change                                            \
Model            ACCESS-ESM1-5                          CMCC-ESM2
Type                  Absolute        Percentage         Absolute
Zone                       Dec    Inc        Dec    Inc       Dec    Inc
Variable
Diatom                     NaN    NaN        NaN    NaN      0.06   6.91
Export                   -0.35   2.27      -2.84  25.10     -1.36   3.55
Iron                     -6.89 -14.77      -1.11  -2.46     14.80  19.37
MLD                      -3.04 -10.43      -6.97 -15.60    -10.34  -5.94
NPP                       0.39   5.14       1.47  27.31      0.82   7.59
Nitrate                  -0.56  -1.10      -2.26  -4.09     -1.40  -1.71
PAR                      -3.18   6.26      -3.54  10.20     -4.10   4.56
SST                       0.56   1.15       0.21   0.42      1.54   0.82
Sea ice fraction         -5.39 -15.96     -28.09 -60.78     -4.65 -16.10

                                                                          \
Model                              EC-Earth3-CC
Type             Percentage            Absolute        Percentage
Zone                    Dec    Inc          Dec    Inc        Dec    Inc
Variable
Diatom                 0.14  20.75        -1.33   2.34      -6.42  12.58
Export                -4.64  15.04        -0.55   2.11      -3.06  11.39
Iron                   7.41  10.23       -25.36  -6.05     -11.07  -3.33
MLD                   -9.83  -7.64       -11.38  -7.75     -18.98 -13.72
NPP                    1.72  19.66         1.95   8.20       3.80  16.93
Nitrate               -6.15  -6.80        -1.09  -0.89      -4.06  -3.30
PAR                   -5.46   9.16        -0.98   5.57      -1.16   7.42
SST                    0.56   0.30         1.24   1.42       0.45   0.52
Sea ice fraction     -99.70 -55.11        -6.00 -14.58     -96.26 -88.30

                                                                             \
Model            IPSL-CM6A-LR                          MPI-ESM1-2-HR
Type                 Absolute        Percentage             Absolute
Zone                      Dec    Inc        Dec    Inc           Dec    Inc
Variable
Diatom                  -2.44   1.08     -12.37   6.31           NaN    NaN
Export                  -1.09   1.20      -5.99   7.51         -0.55   1.30
Iron                   -55.84 -51.40     -24.81 -13.18          1.62  -8.80
MLD                     -6.72 -11.13     -10.20 -17.26         -7.36 -11.07
NPP                      2.20   6.53       4.72  16.00         -5.53  10.53
Nitrate                 -1.18  -2.36      -4.48  -8.59          0.39  -0.15
PAR                      3.40   8.31       5.48  17.87         -3.53   1.12
SST                      1.76   1.30       0.65   0.48          0.60   0.69
Sea ice fraction       -16.12 -17.94     -77.90 -39.96         -6.05 -11.13


Model
Type             Percentage
Zone                    Dec    Inc
Variable
Diatom                  NaN    NaN
Export                -3.51   8.50
Iron                   0.44  -2.52
MLD                  -14.07 -19.04
NPP                   -4.11   8.01
Nitrate                2.22  -0.88
PAR                   -5.54   1.86
SST                    0.22   0.25
Sea ice fraction     -69.69 -52.98

In [106]:
df.to_csv("csv/Zone_change_final.csv")

In [107]:
df = pd.read_csv("csv/Zone_change_final.csv")
df

,Unnamed: 0,Change,Change.1,Change.2,Change.3,Change.4,Change.5,Change.6,Change.7,Change.8,...,Change.10,Change.11,Change.12,Change.13,Change.14,Change.15,Change.16,Change.17,Change.18,Change.19
0,Model,ACCESS-ESM1-5,ACCESS-ESM1-5,ACCESS-ESM1-5,ACCESS-ESM1-5,CMCC-ESM2,CMCC-ESM2,CMCC-ESM2,CMCC-ESM2,EC-Earth3-CC,...,EC-Earth3-CC,EC-Earth3-CC,IPSL-CM6A-LR,IPSL-CM6A-LR,IPSL-CM6A-LR,IPSL-CM6A-LR,MPI-ESM1-2-HR,MPI-ESM1-2-HR,MPI-ESM1-2-HR,MPI-ESM1-2-HR
1,Type,Absolute,Absolute,Percentage,Percentage,Absolute,Absolute,Percentage,Percentage,Absolute,...,Percentage,Percentage,Absolute,Absolute,Percentage,Percentage,Absolute,Absolute,Percentage,Percentage
2,Zone,Dec,Inc,Dec,Inc,Dec,Inc,Dec,Inc,Dec,...,Dec,Inc,Dec,Inc,Dec,Inc,Dec,Inc,Dec,Inc
3,Variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Diatom,NaN,NaN,NaN,NaN,0.06,6.91,0.14,20.75,-1.33,...,-6.42,12.58,-2.44,1.08,-12.37,6.31,NaN,NaN,NaN,NaN
5,Export,-0.35,2.27,-2.84,25.1,-1.36,3.55,-4.64,15.04,-0.55,...,-3.06,11.39,-1.09,1.2,-5.99,7.51,-0.55,1.3,-3.51,8.5
6,Iron,-6.89,-14.77,-1.11,-2.46,14.8,19.37,7.41,10.23,-25.36,...,-11.07,-3.33,-55.84,-51.4,-24.81,-13.18,1.62,-8.8,0.44,-2.52
7,MLD,-3.04,-10.43,-6.97,-15.6,-10.34,-5.94,-9.83,-7.64,-11.38,...,-18.98,-13.72,-6.72,-11.13,-10.2,-17.26,-7.36,-11.07,-14.07,-19.04
8,NPP,0.39,5.14,1.47,27.31,0.82,7.59,1.72,19.66,1.95,...,3.8,16.93,2.2,6.53,4.72,16.0,-5.53,10.53,-4.11,8.01
9,Nitrate,-0.56,-1.1,-2.26,-4.09,-1.4,-1.71,-6.15,-6.8,-1.09,...,-4.06,-3.3,-1.18,-2.36,-4.48,-8.59,0.39,-0.15,2.22,-0.88
10,PAR,-3.18,6.26,-3.54,10.2,-4.1,4.56,-5.46,9.16,-0.98,...,-1.16,7.42,3.4,8.31,5.48,17.87,-3.53,1.12,-5.54,1.86
11,SST,0.56,1.15,0.21,0.42,1.54,0.82,0.56,0.3,1.24,...,0.45,0.52,1.76,1.3,0.65,0.48,0.6,0.69,0.22,0.25
12,Sea ice fraction,-5.39,-15.96,-28.09,-60.78,-4.65,-16.1,-99.7,-55.11,-6.0,...,-96.26,-88.3,-16.12,-17.94,-77.9,-39.96,-6.05,-11.13,-69.69,-52.98

## Season

In [15]:
df = pd.DataFrame(columns=['Model','Variable', 'Percentage change','Absolute change', "Season"])
df

Empty DataFrame
Columns: [Model, Variable, Percentage change, Absolute change, Season]
Index: []

In [47]:
df = pd.read_csv("csv/Season_change.csv")
df = df.replace("Mixed layer depth", "MLD")
df = df.replace("Surface temperature", "SST")
df = df.replace("Sea ice cover", "Sea ice fraction")
df

,Model,Variable,Percentage change,Absolute change,Season
0,ACCESS-ESM1-5,Iron,-3.422902,-1.954334e-08,Summer
1,ACCESS-ESM1-5,Iron,-2.195176,-1.288836e-08,Winter
2,ACCESS-ESM1-5,Export,29.312853,6.639973e+00,Summer
3,ACCESS-ESM1-5,Export,4.748623,1.200639e-02,Winter
4,ACCESS-ESM1-5,NPP,23.932030,3.003913e-08,Summer
...,...,...,...,...,...
79,MPI-ESM1-2-HR,Nitrate,0.799704,1.734737e-04,Winter
80,MPI-ESM1-2-HR,SST,0.350693,9.643250e-01,Summer
81,MPI-ESM1-2-HR,SST,0.169867,4.614258e-01,Winter
82,MPI-ESM1-2-HR,Sea ice fraction,-82.719254,-1.618989e+00,Summer
83,MPI-ESM1-2-HR,Sea ice fraction,-67.499939,-1.157613e+01,Winter

In [48]:
for i in range(len(df["Absolute change"])):
    if df["Variable"][i] == "Nitrate":
        df["Absolute change"][i] = df["Absolute change"][i]*1000
    if df["Variable"][i] == "Iron":
        df["Absolute change"][i] = df["Absolute change"][i]*1e+9
    if df["Variable"][i] == "Diatom":
        df["Absolute change"][i] = df["Absolute change"][i]* 12 * 3.154e+7
    if df["Variable"][i] == "NPP":
        df["Absolute change"][i] = df["Absolute change"][i]* 12 * 3.154e+7

df

/tmp/ipykernel_6694/3638443720.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_6694/3638443720.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_6694/3638443720.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/tmp/ipykernel_6694/3638443720.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Model,Variable,Percentage change,Absolute change,Season
0,ACCESS-ESM1-5,Iron,-3.422902,-19.543336,Summer
1,ACCESS-ESM1-5,Iron,-2.195176,-12.888364,Winter
2,ACCESS-ESM1-5,Export,29.312853,6.639973,Summer
3,ACCESS-ESM1-5,Export,4.748623,0.012006,Winter
4,ACCESS-ESM1-5,NPP,23.932030,11.369211,Summer
...,...,...,...,...,...
79,MPI-ESM1-2-HR,Nitrate,0.799704,0.173474,Winter
80,MPI-ESM1-2-HR,SST,0.350693,0.964325,Summer
81,MPI-ESM1-2-HR,SST,0.169867,0.461426,Winter
82,MPI-ESM1-2-HR,Sea ice fraction,-82.719254,-1.618989,Summer
83,MPI-ESM1-2-HR,Sea ice fraction,-67.499939,-11.576134,Winter

In [49]:
df = df.round({"Percentage change":2, "Absolute change":2})
df.head()

           Model Variable  Percentage change  Absolute change  Season
0  ACCESS-ESM1-5     Iron              -3.42           -19.54  Summer
1  ACCESS-ESM1-5     Iron              -2.20           -12.89  Winter
2  ACCESS-ESM1-5   Export              29.31             6.64  Summer
3  ACCESS-ESM1-5   Export               4.75             0.01  Winter
4  ACCESS-ESM1-5      NPP              23.93            11.37  Summer

In [50]:
df.to_csv("csv/Season_change.csv", header = True, index= False)

### Presenting

In [79]:
df = pd.read_csv("csv/Season_change.csv")
df

,Model,Variable,Percentage change,Absolute change,Season
0,ACCESS-ESM1-5,Iron,-3.42,-19.54,Summer
1,ACCESS-ESM1-5,Iron,-2.20,-12.89,Winter
2,ACCESS-ESM1-5,Export,29.31,6.64,Summer
3,ACCESS-ESM1-5,Export,4.75,0.01,Winter
4,ACCESS-ESM1-5,NPP,23.93,11.37,Summer
...,...,...,...,...,...
79,MPI-ESM1-2-HR,Nitrate,0.80,0.17,Winter
80,MPI-ESM1-2-HR,SST,0.35,0.96,Summer
81,MPI-ESM1-2-HR,SST,0.17,0.46,Winter
82,MPI-ESM1-2-HR,Sea ice fraction,-82.72,-1.62,Summer
83,MPI-ESM1-2-HR,Sea ice fraction,-67.50,-11.58,Winter

In [80]:
df = pd.melt(df, id_vars=["Model", "Variable", "Season"], value_vars=["Percentage change", "Absolute change"],
             var_name='Type', value_name='Change')
df

             Model          Variable  Season               Type  Change
0    ACCESS-ESM1-5              Iron  Summer  Percentage change   -3.42
1    ACCESS-ESM1-5              Iron  Winter  Percentage change   -2.20
2    ACCESS-ESM1-5            Export  Summer  Percentage change   29.31
3    ACCESS-ESM1-5            Export  Winter  Percentage change    4.75
4    ACCESS-ESM1-5               NPP  Summer  Percentage change   23.93
..             ...               ...     ...                ...     ...
163  MPI-ESM1-2-HR           Nitrate  Winter    Absolute change    0.17
164  MPI-ESM1-2-HR               SST  Summer    Absolute change    0.96
165  MPI-ESM1-2-HR               SST  Winter    Absolute change    0.46
166  MPI-ESM1-2-HR  Sea ice fraction  Summer    Absolute change   -1.62
167  MPI-ESM1-2-HR  Sea ice fraction  Winter    Absolute change  -11.58

[168 rows x 5 columns]

In [81]:
df = df.pivot_table(index="Variable", columns=["Model", "Type", "Season"], values=["Change"])
df

                          Change                                  \
Model              ACCESS-ESM1-5
Type             Absolute change        Percentage change
Season                    Summer Winter            Summer Winter
Variable
Diatom                       NaN    NaN               NaN    NaN
Export                      6.64   0.01             29.31   4.75
Iron                      -19.54 -12.89             -3.42  -2.20
MLD                        -0.64 -16.47             -2.83 -17.20
NPP                        11.37   0.04             23.93  59.19
Nitrate                    -1.32  -1.00             -4.98  -3.66
PAR                         0.48   0.43              0.29  40.54
SST                         1.58   0.81              0.57   0.30
Sea ice fraction           -7.44 -17.02            -83.93 -76.31

                                                                  \
Model                  CMCC-ESM2
Type             Absolute change        Percentage change
Season                    Summer Winter            Summer Winter
Variable
Diatom                     -2.44   0.05             -3.37  -4.90
Export                      6.69  -0.80             25.26  -3.99
Iron                       11.98  22.90              7.41  11.20
MLD                         0.25  -8.28              1.07  -7.33
NPP                        -2.13   0.07             -2.28 -11.19
Nitrate                    -1.82  -1.28             -8.60  -4.88
PAR                        -5.42   0.08             -3.42  22.32
SST                         1.32   0.81              0.48   0.30
Sea ice fraction           -5.21  -9.79            -89.86 -77.86

                                                                  \
Model               EC-Earth3-CC
Type             Absolute change        Percentage change
Season                    Summer Winter            Summer Winter
Variable
Diatom                     -1.40   0.38             -4.22  69.12
Export                     -0.22  -0.16             -0.79  -5.64
Iron                         NaN    NaN               NaN    NaN
MLD                        -0.34 -12.62             -1.47 -16.56
NPP                         2.37   1.40              2.70  91.04
Nitrate                    -1.00  -0.77             -4.03  -2.72
PAR                        -8.21   0.71             -4.21  41.66
SST                         1.77   1.15              0.64   0.42
Sea ice fraction           -0.35 -15.67           -100.00 -95.51

                                                                  \
Model               IPSL-CM6A-LR
Type             Absolute change        Percentage change
Season                    Summer Winter            Summer Winter
Variable
Diatom                     -6.13   0.15            -13.09  35.20
Export                     -2.11   0.01             -6.11   0.54
Iron                      -41.18 -44.69            -17.81 -15.32
MLD                        -1.38 -11.44             -5.55 -13.80
NPP                        -0.79   0.94             -0.70  49.18
Nitrate                    -0.84  -1.96             -3.61  -6.63
PAR                        -0.26   0.11             -0.16  18.59
SST                         2.37   0.85              0.87   0.31
Sea ice fraction           -8.30 -13.85            -87.36 -68.54


Model              MPI-ESM1-2-HR
Type             Absolute change        Percentage change
Season                    Summer Winter            Summer Winter
Variable
Diatom                       NaN    NaN               NaN    NaN
Export                      2.61  -0.02              5.43  -7.58
Iron                       -1.27  -2.15             -0.88  -0.47
MLD                         0.26 -16.53              1.30 -18.86
NPP                       -12.22   0.01             -3.57  33.04
Nitrate                     0.22   0.17              2.76   0.80
PAR                       -10.88   0.34             -7.37  27.03
SST                         0.96   0.46              0.35   0.17
Sea ice fraction           -1.62 -11.58            -82.72 -67.50

In [82]:
df.to_csv("csv/Season_change_final.csv")

In [83]:
df = pd.read_csv("csv/Season_change_final.csv")
df

,Unnamed: 0,Change,Change.1,Change.2,Change.3,Change.4,Change.5,Change.6,Change.7,Change.8,...,Change.10,Change.11,Change.12,Change.13,Change.14,Change.15,Change.16,Change.17,Change.18,Change.19
0,Model,ACCESS-ESM1-5,ACCESS-ESM1-5,ACCESS-ESM1-5,ACCESS-ESM1-5,CMCC-ESM2,CMCC-ESM2,CMCC-ESM2,CMCC-ESM2,EC-Earth3-CC,...,EC-Earth3-CC,EC-Earth3-CC,IPSL-CM6A-LR,IPSL-CM6A-LR,IPSL-CM6A-LR,IPSL-CM6A-LR,MPI-ESM1-2-HR,MPI-ESM1-2-HR,MPI-ESM1-2-HR,MPI-ESM1-2-HR
1,Type,Absolute change,Absolute change,Percentage change,Percentage change,Absolute change,Absolute change,Percentage change,Percentage change,Absolute change,...,Percentage change,Percentage change,Absolute change,Absolute change,Percentage change,Percentage change,Absolute change,Absolute change,Percentage change,Percentage change
2,Season,Summer,Winter,Summer,Winter,Summer,Winter,Summer,Winter,Summer,...,Summer,Winter,Summer,Winter,Summer,Winter,Summer,Winter,Summer,Winter
3,Variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Diatom,NaN,NaN,NaN,NaN,-2.44,0.05,-3.37,-4.9,-1.4,...,-4.22,69.12,-6.13,0.15,-13.09,35.2,NaN,NaN,NaN,NaN
5,Export,6.64,0.01,29.31,4.75,6.69,-0.8,25.26,-3.99,-0.22,...,-0.79,-5.64,-2.11,0.01,-6.11,0.54,2.61,-0.02,5.43,-7.58
6,Iron,-19.54,-12.89,-3.42,-2.2,11.98,22.9,7.41,11.2,NaN,...,NaN,NaN,-41.18,-44.69,-17.81,-15.32,-1.27,-2.15,-0.88,-0.47
7,MLD,-0.64,-16.47,-2.83,-17.2,0.25,-8.28,1.07,-7.33,-0.34,...,-1.47,-16.56,-1.38,-11.44,-5.55,-13.8,0.26,-16.53,1.3,-18.86
8,NPP,11.37,0.04,23.93,59.19,-2.13,0.07,-2.28,-11.19,2.37,...,2.7,91.04,-0.79,0.94,-0.7,49.18,-12.22,0.01,-3.57,33.04
9,Nitrate,-1.32,-1.0,-4.98,-3.66,-1.82,-1.28,-8.6,-4.88,-1.0,...,-4.03,-2.72,-0.84,-1.96,-3.61,-6.63,0.22,0.17,2.76,0.8
10,PAR,0.48,0.43,0.29,40.54,-5.42,0.08,-3.42,22.32,-8.21,...,-4.21,41.66,-0.26,0.11,-0.16,18.59,-10.88,0.34,-7.37,27.03
11,SST,1.58,0.81,0.57,0.3,1.32,0.81,0.48,0.3,1.77,...,0.64,0.42,2.37,0.85,0.87,0.31,0.96,0.46,0.35,0.17
12,Sea ice fraction,-7.44,-17.02,-83.93,-76.31,-5.21,-9.79,-89.86,-77.86,-0.35,...,-100.0,-95.51,-8.3,-13.85,-87.36,-68.54,-1.62,-11.58,-82.72,-67.5